# Generated by Django 4.2.9 on 2024-04-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cartorder_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='users.cartorder'),
        ),
    ]
